apiVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: express-api
---    
apiVersion: v1
kind: Deployment
metadata:
  name: express-api
  labels:
    app: express-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: rootduck/express-api:1.0.0
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: express-api-configmap
                  key: mongodb_host
            - name: MONGODB_NAME
              valueFrom:
                configMapKeyRef:
                  name: express-api-configmap
                  key: mongodb_name
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: express-api-secret
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: express-api-secret
                  key: mongodb_password