apiVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: express-api
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api
  labels:
    app: express-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: rootduck/express-api:1.0.2
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: express-api-configmap
                  key: db_host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: express-api-configmap
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: express-api-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: express-api-secret
                  key: db_password